DEVICE = "cuda"
LR = 0.0001
EPOCH = 2
TRAIN_BATCH_SIZE = 1
TEST_BATCH_SIZE = 1
NUM_WORKERS = 8
class_weight = [0.02, 1.02]
TRAIN_PATH = "../tvt_dataset/data/train_index_new.txt"
VALIDATION_PATH =  "../tvt_dataset/data/val_index_new.txt"
TRAINED_WEIGHTS_PATH = "./trained_weights/"
TEST_PATH = "../tvt_dataset/data/test_index_0530.txt"
SAVE_PATH = "./train_save/"
SAVE_PATH_VAL = "./val_save/"
SAVE_PATH_TEST_1 = "./test_save_1/"
SAVE_PATH_TEST_2 = "./test_save_2/"
TRAIN_EVAL_BATCH = 100