class_weight = [0.02, 1.02]
LR = 0.001
EPOCH = 2
BATCH_SIZE = 5
NUM_WORKERS = 8
TRAIN_PATH = "E:/WPI_Courses/Deep_Learning/Project/trainset/trainset/train_index.txt"
VALIDATION_PATH = "E:/WPI_Courses/Deep_Learning/Project/trainset/trainset/val_index.txt"
TEST_PATH = "../../../tvt_dataset/data/test_index_0530.txt"
SAVE_PATH = "E:/WPI_Courses/Deep_Learning/Project/Lane-Detection-using-SCNN-and-ConvLSTM/train_save/"
DEVICE = "cpu"